#!/bin/sh

# Copyright (c) 2013, Frank Terbeck <ft@bewatermyfriend.org>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHAN-
# TABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHAT-
# SOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION
# OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
# CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

pc=''

init_pc () {
    gitdir=$(git rev-parse --git-dir)
    if [ "$?" != 0 ]; then
        echo "git rev-parse failed!"
        exit 1
    fi
    pc="${gitdir}/zsh-am.post-command"
}

should_try_stdin () {
    # If there is no non-option argument or the only non-option argument is a
    # single dash ("-"), read from stdin and use that input as the mbox to work
    # on.
    [ "$#" -eq 0 ] && return 0
    [ "$#" -eq 1 ] && [ "x$1" = "x-" ] && return 0
    return 1
}

process_mbox () {
    zsh-am-xseq2subject "$1" || {
        echo "zsh-am: xseq2subject failed! (mbox: \"$1\")"
        return 1
    }
    zsh-am-and-changelog "$1" || {
        echo "zsh-am: am-and-changelog failed! (mbox: \"$1\")"
        return 1
    }
    return 0
}

is_opt () {
    case "$1" in
        -) return 1;;
        -*) return 0;;
        *) return 1;;
    esac
}

while is_opt "$1"; do
    case $1 in
        --)
            shift
            break
            ;;
        -cwd)
            if [ $# -eq 1 ]; then
                echo "zsh-am: -cwd needs a parameter!"
                exit 1
            fi
            shift
            cd "$1" || {
                echo "zsh-am: Failed to change working directory!"
                exit 1
            }
            shift
            ;;
        -init)
            init_pc
            cat > "$pc" <<EOF
#!/bin/sh

# Save old commit message for later use.
msg=\$(git log --format='%B' -1 'HEAD')

# Add ChangeLog entry for the last commit. The options given largely enable
# zsh specific operation of \`genchangelog':
#
#   -P: Take the topmost entry of the current ChangeLog into account: If
#       there already is a change by the new author from the same date,
#       then add a new bullet-point to that stanza. Only create a completely
#       new entry otherwise. This keeps the ChangeLog neat, in case you call
#       zsh-am on a mailbox with a lot of changes of a single author in
#       direct succession (think: patch-series).
#
#   -T: Use the current date instead of the date from the commit-mail. This
#       keeps the date-stamps in ChangeLog linear even when importing old
#       commits that have been around on the mailing list for a long time.
#
#   -H: Do _NOT_ add hash-sums to ChangeLog entries: Since we'll be amending
#       the last commit in the next step, the hash-sum will change. That
#       means we would end up with invalid hash-sums in the ChangeLog file,
#       which has no value at all.
#
#   -X: Assume that commit-message have an X-Seq: prefix and act accordingly.
#       Since \`zsh-am' calls out to \`zsh-am-xseq2subject' before calling
#       \`genchangelog', that should just work.
genchangelog -P -T -H -X -o 'HEAD^' -n 'HEAD'

# Add Changelog to the staged changes.
git add ChangeLog

# Finally amend the current commit with the newly added ChangeLog entry,
# using the old commit message we saved to \$msg before.
git commit --amend -m"\$msg"
EOF
            exit 0
            ;;
        -*) printf 'Unknown option: `%s'\''\n' "$1";;
    esac
done

init_pc
if [ ! -e "$pc" ]; then
    echo 'zsh-am-and-changelog: `'"$pc"\'' missing!'
    echo 'Forgot to run "zsh-am -init"?'
    exit 1
fi

if should_try_stdin; then
    mbox=$(mktemp "${TMPDIR:-/tmp}"/zsh-am.mbox.XXXXXXXXXXXX) || {
        echo "zsh-am: Could not create temporary file. Giving up."
        exit 1
    }
    cat > "$mbox"
    process_mbox "$mbox"
    rm "$mbox" || {
        echo "zsh-am: Failed to remove \"$mbox\"!"
        exit 1
    }
else
    for mbox in "$@"; do
        process_mbox "$mbox" || {
            echo "zsh-am: Processing mailbox failed: \"$mbox\"; Exiting..."
            exit 1
        }
    done
fi
exit 0
